---
format_version: 3
pipelines:
  gocd-cli:
    group: go-cd-contrib
    materials:
      github:
        git: https://github.com/gocd-contrib/gocd-cli

    stages:
      - build:
          elastic_profile_id: ecs-golang-build
          artifacts:
            - build:
                source: dist/
          tasks:
          - exec:
              command: /bin/bash
              arguments:
                - build.sh
                - --verbose
                - --prod
